sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - REGISTRY_USER=vektory79
    - secure: bxo1fW4rn4BP53WM0BVVC8tyv56gKBdWKOnlVaBFTlStGbLSb+rToE5b7dQKCF9INwiS/wkoJqrezpsbqezpYyfstobNqC0UZiPzY3qJLCi/dscqVrO0GW05IY1AB31ZoXVwfUHJ/T6lrNYFQtbxR1sncW2XwYH8sCjATzsLX+KyFmZXG82pHWaQfytu/aSMX8JJ1wQYgGwQ4tdAXfUffeVIRNwY8d2Vcc3OcDekKeVRY7JjmKOrUT9NCFAp4oFQGQcskz/4clFb7WoW9qtmOfZAFOIi/a86op8B27SXSBNZ4KkZjCreK08q7L+6nD0cwOtP8LSbowne4HqWuzPtvCW5y9UKJEbqeo0xHCAFSDIfK+SsNi04KihMLE6jpFvXWy7U/Cd/8j5wiHDJitCfDqNNimxKGkJDmEDLC/nN2cE1GIil8f4STDh0P6Nltl72rzKunY2NOLTy/twRQvQsz+spaJgSN85H1dxTmVaqKZTtWPeF4WQvVv6WZ7tUFN0MUS9EuUJUQPpctMzIfLZ3q6IuHUnq8M3JQxJUB4ITcBAvcKqUUqHLw+oMuG+O53NsEvH5+Cf+AMB1MeLvQZKX+T+L3sid7BUgQ7hHu7e8oL5dg8dhHrQN3rkj7oJY5Y+doxgQ6Xr59sP6hB7hp5S/TtKGiMSVH4yJTwkElytPnCw=
script:
  - ./build.sh -pc

after_script:
  - docker images
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" javister-docker-docker.bintray.io

deploy:
  provider: script
  script: ./build.sh -rdc
  on:
    branch: master
